import { z } from "zod";
export declare const createLeadSchema: z.ZodObject<{
    firstName: z.ZodString;
    lastName: z.ZodString;
    company: z.ZodOptional<z.ZodString>;
    email: z.ZodUnion<[z.ZodOptional<z.ZodString>, z.ZodLiteral<"">]>;
    phone: z.ZodOptional<z.ZodString>;
    status: z.ZodOptional<z.ZodString>;
    sourceId: z.ZodOptional<z.ZodString>;
    ownerId: z.ZodOptional<z.ZodString>;
    interestedProjectId: z.ZodOptional<z.ZodString>;
    telegramHandle: z.ZodOptional<z.ZodString>;
    websiteInquiryUrl: z.ZodOptional<z.ZodString>;
    budgetMinETB: z.ZodOptional<z.ZodNumber>;
    budgetMaxETB: z.ZodOptional<z.ZodNumber>;
    timeline: z.ZodOptional<z.ZodString>;
    preferredBedrooms: z.ZodOptional<z.ZodNumber>;
    preferredPaymentPlan: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export type CreateLeadSchemaInput = z.infer<typeof createLeadSchema>;
export declare const updateLeadSchema: z.ZodObject<{
    firstName: z.ZodOptional<z.ZodString>;
    lastName: z.ZodOptional<z.ZodString>;
    company: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    email: z.ZodOptional<z.ZodUnion<[z.ZodOptional<z.ZodString>, z.ZodLiteral<"">]>>;
    phone: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    status: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    sourceId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    ownerId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    interestedProjectId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    telegramHandle: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    websiteInquiryUrl: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    budgetMinETB: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    budgetMaxETB: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    timeline: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    preferredBedrooms: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    preferredPaymentPlan: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, z.core.$strip>;
export type UpdateLeadSchemaInput = z.infer<typeof updateLeadSchema>;
